### ISSUE TITLE
Implement transaction status screen

### ISSUE THREAD

**Issue by TalgatNurdinov** [horizontalsystems/bank-wallet-ios-app#41]
Transaction status screen opened by clickable status in info. Sender/Receiver and ID addresses clickable for copying. "Block" cell should be disabled when status in processing

Screens

- Transaction Status zpl://screen?sid=5b8f60bd5dd19031dbad0d75&pid=5b167c731d079e4122e946b7
- Transaction status processing zpl://screen?sid=5b8f60be25531c63591f37ad&pid=5b167c731d079e4122e946b7

![transaction status](https://user-images.githubusercontent.com/42367908/45082740-d294ca80-b11b-11e8-9b4d-dc515c823d87.png)

https://scene.zeplin.io/project/5b167c731d079e4122e946b7

**Comment by esengulov** [comment]
duplicate https://github.com/horizontalsystems/bank-wallet-ios-app/issues/58
