### ISSUE TITLE
Add translations: German + Russian languages

### ISSUE THREAD

**Issue by esengulov** [horizontalsystems/bank-wallet-ios-app#74]
- [x] add German translations
- [x] add Russian translations

**Comment by Dianaaiym** [comment]
Done! RU and DE languages

**Comment by esengulov** [comment]
@

> Done! RU and DE languages

please review all translated texts and make sure that that they are release ready

- [ ] English
- [ ] Russian
- [ ] German

**Comment by esengulov** [comment]
> @
> 
> > Done! RU and DE languages
> 
> please review all translated texts and make sure that that they are release ready
> 
> * [x]  English
> * [x]  Russian
> * [x]  German

 ok, we are ready to start with the other languages
please set up a new issues both for iOS/Android for the next 3 languages
